name: Desplegar Infraestructura

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - name: Configurar Vault
        uses: hashicorp/vault-action@v2.1.1
        id: vault
        with:
          # URL de tu instancia de Vault
          url: ${{ secrets.VAULT_ADDR }} 
          # Token de autenticación de Vault
          token: ${{ secrets.VAULT_TOKEN }}
          # Path en Vault donde están los secretos de Azure
          secrets: "azure/creds/github-roles" 
          # Formato de salida de los secretos (environment variables)
          exportEnv: true 
      - name: Inicializar Terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
      - name: Validar configuración de Terraform
        run: terraform validate
      - name: Aplicar Terraform
        run: terraform apply -auto-approve
