name: Prueba de Lectura de Secretos de Vault

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  test_vault_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug
        run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Print Role ID and Secret ID
        run: |
          echo "Role ID: ${{ secrets.VAULT_ROLE_ID }}"
          echo "Secret ID: ${{ secrets.VAULT_SECRET_ID }}"

      - name: Retrieve secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secretos/prueba prueba_username | PRUEBA_USER_NAME ;
            secretos/prueba password | PRUEBA_PASSWORD

      - name: Evaluate Secret Values
        run: |
          USER = {{ env.PRUEBA_USER_NAME }}
          PASSWORD = {{ steps.import-secrets.outputs.PRUEBA_PASSWORD }}
          
          if [ "$USER" == "SoyUnTest" ] && [ "$PASSWORD" == "H4x0r" ]; then
            echo "Verdadero"
          else
            echo "Falso"
          fi
