name: Prueba de Lectura de Secretos de Vault

on:
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  test_vault_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Vault Environment
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }} # Dirección de tu instancia de Vault
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: |
          # Autenticación con AppRole y obtención del token de Vault
          vault login -method=approle -role-id=$VAULT_ROLE_ID -secret-id=$VAULT_SECRET_ID
          echo "VAULT_TOKEN=$(vault write -f auth/approle/login role_id=$VAULT_ROLE_ID secret_id=$VAULT_SECRET_ID -format=json | jq -r .auth.client_token)" >> $GITHUB_ENV

      - name: Read Vault Secret
        id: read_secret # Asigna un ID al paso para acceder a sus resultados
        env:
          VAULT_TOKEN: ${{ env.VAULT_TOKEN }}
        run: |
          # Lee el secreto "prueba" del secret engine kv
          SECRET=$(vault kv get -format=json secretos/prueba)

          # Extrae los valores de prueba_user y password usando jq
          echo "TEST_USER=$(echo $SECRET | jq -r '.data.data.prueba_user')" >> $GITHUB_ENV
          echo "PASSWORD=$(echo $SECRET | jq -r '.data.data.password')" >> $GITHUB_ENV

      - name: Evaluate Secret Values
        run: |
          if [ "$TEST_USER" == "SoyUnTest" ] && [ "$PASSWORD" == "H4x0r" ]; then
            echo "Verdadero"
          else
            echo "Falso"
          fi
